name: publish
on: [push]
jobs:
  publish-node-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the node app Docker image
        run:
          docker build . --tag https://github.com/P-Aliz/projektkubectl-doc-img:latest
          docker run https://github.com/P-Aliz/projektkubectl-doc-img
          docker push ghttps://github.com/P-Aliz/projektkubectl-doc-img